name: kubernetes

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk
  schedule:
    - cron: '19 18 * * 4'
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: kubernetes

jobs:
  test:
    name: test kubernetes
    runs-on: ubuntu-latest
    env:
      GOVER: 1.17
    steps:
      - uses: actions/checkout@v2

      - name: install k8s
        run: |
          curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE=777 sh -
          cat /etc/rancher/k3s/k3s.yaml
          mkdir -p ~/.kube
          cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
          kubectl cluster-info
          kubectl get po

      - name: add spice components to cluster
        run: |
          kubectl apply -f trader-configmap.yaml
          kubectl apply -f spiceai-deployment.yaml
          kubectl rollout status deployment/spiceai-deployment --timeout=240s
          kubectl expose deployment spiceai-deployment --type=LoadBalancer
          kubectl get service --all-namespaces
          sleep 30
          kubectl get service --all-namespaces

      - name: fetch recommendation
        run: |
          curl http://localhost:8000/api/v0.1/pods/trader/recommendation