name: serverops

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk
  schedule:
    - cron: '19 18 * * 4'
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: serverops

jobs:
  test:
    name: test serverops
    runs-on: ubuntu-latest
    env:
      GOVER: 1.17
    steps:
      - uses: actions/checkout@v2

      - name: bring up influxdb/telegraf
        run: docker-compose up -d

      - name: update PATH
        run: |
          echo "PATH=~/.spice/bin:$PATH" >> $GITHUB_ENV

      - name: install Spice.ai
        run: |
          curl https://install.spiceai.org | /bin/bash

      - name: attempt to reach influxdb after 30 seconds
        run: |
          sleep 30
          curl http://localhost:8086

      - name: spice run
        run: |
          source set-spice-vars.sh
          spice run &

      - name: wait for Spice.ai runtime healthy
        run: |
          timeout 30 bash -c 'while [[ "$(curl -s -w 200 http://localhost:8000/health)" != "ok200" ]]; do sleep 1; done' || false

      - name: fetch diagnostics
        run: |
          curl http://localhost:8000/api/v0.1/diagnostics

      - name: get sample pod
        run: |
          spice add samples/serverops

      - name: start training
        run: |
          spice train serverops

      - name: fetch pods
        run: |
          curl -s http://localhost:8000/api/v0.1/pods | jq
      
      - name: fetch observations
        run: |
          curl http://localhost:8000/api/v0.1/pods/serverops/observations
